<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
           <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control quantityControl">
                <span class="decreaseQty qtybutton">-</span>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="1"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty qtybutton"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                       <span class="increaseQty qtybutton">+</span>
            </div>
         </div>
         <?php endif; ?>


            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" style="width:50%">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <div class="add-to-links nee "><a href="#" class="link-wishlist" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' data-action="add-to-wishlist"></a>
    <br><?php echo __('Add to wishlist')?>
</div>
<?php else: ?>
    <div class="actions">
        <button type="text"
                title="Sold Out"
                class="action primary tocart"
                id="product-addtocart-button" style="width:100%">
            <span>Sold Out</span>
        </button>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
<script type="text/javascript">
require(['jquery'],function(){



    jQuery(document).ready(function(){
        jQuery(".increaseQty").click(function(e){
            e.preventDefault();
            var qty=parseInt(jQuery("#qty").val());
            qty+=1;
            jQuery("#qty").val(qty);
        });
        jQuery(".decreaseQty").click(function(e){
            e.preventDefault();
            var qty=parseInt(jQuery("#qty").val());
            if(qty<=1){
                return;
            }else{
                qty-=1;
                jQuery("#qty").val(qty);
            }
        });
    });


    
});
</script>

