<?php


$host = "localhost"; // MySQL host name eg. localhost
$user = "cmdbuser"; // MySQL user. eg. root ( if your on localserver)
$password = "5Rr#u@PGm6FKHg@3L4cA"; // MySQL user password  (if password is not set for your root user then keep it empty )
//$password = "Cr@ft123$";
$database = "craft_live"; // MySQL Database name
//$database = "Craftlive_15_06_2021";
// Connect to MySQL Database
$con = new mysqli($host, $user, $password, $database);

// Check connection
if ($con->connect_error) {
    die("Connection failed: " . $con->connect_error);
}

// get Users
$from_date = date('Y-m-d',strtotime($_POST['from']));
$to_date = date('Y-m-d',strtotime($_POST['to']));
$from_date = $from_date." 00:00:00";
$to_date = $to_date." 23:59:59";

/*$query = "select cst_invoice.custom_invoice_number as 'Invoice No.',si.created_at as 'Date',CONCAT(so.customer_firstname,' ',so.customer_lastname) as 'Debit Party Ledger','Debtors Online',(select customer.value from customer_entity_varchar as customer where customer.attribute_id=221 and customer.entity_id=so.customer_id) as 'Party GSTIN',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',CONCAT('Sales Local @ ',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0),'%'),CONCAT('Sales Central @ ',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0),'%')) as 'Credit sales ledger',(select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping') as 'Place Of Supply',sii.name as 'Item Name','Pcs','','Main Location',sii.qty as 'Qty',(sii.base_price-IF(sii.discount_amount IS NULL,0,sii.discount_amount)) as 'Sale Rate',(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)) as 'Basic Amount',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0) as 'TAX(%)',(select cpev.value from catalog_product_entity_varchar as cpev where cpev.entity_id=sii.product_id and cpev.attribute_id=210 limit 1) as 'HSN Code',so.increment_id as 'Narration', IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=28,(sii.tax_amount/2),''),'') as 'Output CGST @ 14%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=3,(sii.tax_amount/2),''),'') as 'Output CGST @ 1.50%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=5,(sii.tax_amount/2),''),'') as 'Output CGST @ 2.5%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=12,(sii.tax_amount/2),''),'') as 'Output CGST @ 6%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=18,(sii.tax_amount/2),''),'') as 'Output CGST @ 9%'"; */
$query = "select cst_invoice.custom_invoice_number as 'Invoice No.',si.created_at as 'Date',CONCAT(so.customer_firstname,' ',so.customer_lastname) as 'Debit Party Ledger','Debtors Online',(select customer.value from customer_entity_varchar as customer where customer.attribute_id=221 and customer.entity_id=so.customer_id) as 'Party GSTIN',(select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping') as 'Place Of Supply',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',CONCAT('Sales Local @ ',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0),'%'),CONCAT('Sales Central @ ',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0),'%')) as 'Credit sales ledger',sii.name as 'Item Name','Pcs','','Main Location',sii.qty as 'Qty',(sii.base_price-IF(sii.discount_amount IS NULL,0,sii.discount_amount)) as 'Sale Rate',(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)) as 'Basic Amount',ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0) as 'TAX(%)',(select cpev.value from catalog_product_entity_varchar as cpev where cpev.entity_id=sii.product_id and cpev.attribute_id=210 limit 1) as 'HSN Code',so.increment_id as 'Narration', IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=28,(sii.tax_amount/2),''),'') as 'Output CGST @ 14%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=3,(sii.tax_amount/2),''),'') as 'Output CGST @ 1.50%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=5,(sii.tax_amount/2),''),'') as 'Output CGST @ 2.5%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=12,(sii.tax_amount/2),''),'') as 'Output CGST @ 6%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=18,(sii.tax_amount/2),''),'') as 'Output CGST @ 9%'";
$query = $query.", IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=28,(sii.tax_amount/2),''),'') as 'Output SGST @ 14%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=3,(sii.tax_amount/2),''),'') as 'Output SGST @ 1.50%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=5,(sii.tax_amount/2),''),'') as 'Output SGST @ 2.5%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=12,(sii.tax_amount/2),''),'') as 'Output SGST @ 6%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=18,(sii.tax_amount/2),''),'') as 'Output SGST @ 9%'"; //SGST

$query = $query.", IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')!='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=12,(sii.tax_amount),''),'') as 'Output IGST @ 12%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')!='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=18,(sii.tax_amount),''),'') as 'Output IGST @ 18%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')!='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=28,(sii.tax_amount),''),'') as 'Output IGST @ 28%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')!='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=3,(sii.tax_amount),''),'') as 'Output SGST @ 3%',IF((select soa.region from sales_order_address as soa where soa.parent_id=so.entity_id and soa.address_type='shipping')!='Haryana',IF(ROUND(((sii.tax_amount/(sii.base_row_total-IF(sii.discount_amount IS NULL,0,sii.discount_amount)))*100),0)=5,(sii.tax_amount),''),'') as 'Output IGST @ 5%'"; //IGST
//from sales_invoice as si LEFT JOIN sales_order as so ON si.order_id=so.entity_id";
//$query = $query."";
$query = $query." from sales_invoice as si LEFT JOIN sales_order as so ON si.order_id=so.entity_id LEFT JOIN sales_invoice_item as sii ON si.entity_id=sii.parent_id LEFT JOIN custom_c_invoice_number as cst_invoice ON si.increment_id = cst_invoice.invoice_number where si.created_at >= '".$from_date."' AND si.created_at <= '".$to_date."'";
//echo $query;
//$query = "SELECT customer_firstname,increment_id,created_at,base_grand_total,customer_email FROM sales_order";
if (!$result = mysqli_query($con, $query)) {
    exit(mysqli_error($con));
}

$users = array();
if (mysqli_num_rows($result) > 0) {
    while ($row = mysqli_fetch_assoc($result)) {
        $users[] = $row;
    }
}

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=Order_report.csv');
$output = fopen('php://output', 'w');
fputcsv($output, array('Invoice No', 'Date', 'Debit Party Ledger', 'Party Group', 'Party GSTIN', 'Place Of Supply', 'Credit sales ledger', 'Item Name', 'Item unit', 'Item Group', 'Godown Name', 'Qty', 'Sale Rate', 'Basic Amount', 'TAX(%)', 'HSN Code', 'Narration', 'Output CGST @ 14%', 'Output CGST @ 1.50%', 'Output CGST @ 2.5%', 'Output CGST @ 6%', 'Output CGST @ 9%', 'Output SGST @ 14%', 'Output SGST @ 1.50%', 'Output SGST @ 2.5%', 'Output SGST @ 6%', 'Output SGST @ 9%', 'Output IGST @ 12%', 'Output IGST @ 18%', 'Output IGST @ 28%', 'Output IGST @ 3%', 'Output IGST @ 5%', 'Led'));
if (count($users) > 0) {
    foreach ($users as $row) {
        fputcsv($output, $row);
    }
}
?>

