<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
/** @var \Magento\Framework\UrlInterface $urlInterface */
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$urlInterface->getCurrentUrl();
if(!$customerSession->isLoggedIn())
{
?>
<style>
.close_area button {
    margin-right: 14px;
    margin-top: 5px;
    font-size: 35px;
    font-weight: 900;
    color: #838383;
    opacity: 1;
}

.welcome_area_container {
    border: 2px solid #838383;
    padding: 7px;
    text-align: center;
        border-radius:2px;
        color:black;
}

.welcome_area_container h2 {
    font-size: 60px;
        font-family: 'Italianno', cursive;
            margin-bottom: 0px;
        color:black;
}

.welcome_area_container h3 {
    font-size: 70px;
        font-family: 'Italianno', cursive;
        color:black;
}

.welcome_area_container span {
    display: block;
    font-size: 45px;
    font-weight: 600;
}

.welcome_area_container p {

    font-size: 25px;

}
.btn-common {
    background: #ce982b;
    padding: 8px 0px;
    width: 60%;
    margin: 15px auto;
    border-radius: 50px;
    line-height: 20px;
}

.btn-common a{
    color: #3f3a41;
    font-weight: 600;
    font-size: 20px;
    line-height: 20px;
        text-decoration: none;
}

.border_line {
    width: 62%;
    height: 2px;
    background: #adadad;
    margin: 0 auto;
}
.modal-popup-custom-class .modal-footer{display:none;}
.modal-popup-custom-class .modal-header{padding: 5px;}
.modal-popup-custom-class .modal-inner-wrap{ width: 500px; }
.modal-popup-custom-class .modal-content{padding-left:5px;padding-right:5px;padding-bottom:5px!important;}
.modal-popup-custom-class .action-close {margin: 25px;}

@media only screen and (max-width: 600px) {
.welcome_area_container {
    border: 2px solid #838383;
    padding: 12px 30px;
    text-align: center;
    border-radius: 2px;
        margin-top:20px;
}

.welcome_area_container h2 {
    font-size: 32px;
    margin-top: 10px;
}
 .welcome_area_container h3 {
    font-size: 30px;
}
 .welcome_area_container span {
    display: block;
    font-size: 38px;
    font-weight: 600;
}
.btn-common {
    background: #ce982b;
    padding: 15px 0px;
    width: 100%;
    margin: 13px auto;
    border-radius: 50px;
    line-height: 18px;
}
.btn-common a {

    font-size: 18px;

}

.close_area button {
    margin-right: 14px;
    margin-top: 24px;
    font-size: 35px;
    font-weight: 900;
    color: #838383;
    opacity: 1;
}
.modal-popup-custom-class .modal-footer{  display:none; }
.modal-popup-custom-class .action-close {
        top: 20px;
        right: 10px;
}
.modal-popup-custom-class .modal-header {
    padding: 0px;
}

}
@media only screen and (max-width: 767px)
{
.modal-popup-custom-class .modal-inner-wrap[class]
{
    width: fit-content;
	margin-right: 46px;
}
.modal-popup-custom-class{height: fit-content;
    margin: auto;}
}
</style>

<div id="myModal" class="callfor-popup modal fade" style="display:none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <!--<div class="modal-body main_border_area">
                        <div class="close_area">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>-->
                                 <div class="welcome_area_container">
                                        <h2 style="text-transform: capitalize;">Instant Checkout</h2>
                                        <div class="border_line"></div>
                                        <h3 style="margin-bottom:-5px;text-transform: capitalize;">Offer</h3>
                                        <p>now with Coupon : SAVE10
                                         <span>And get 10% discount</span>
                                        on your order.</p>
                                        <!--<div class="btn-common regis-area"><a href="javascript:void(0)" class="mt_signin">Register Now</a></div>
                                        <div class="btn-common already-regis-area"><a href="javascript:void(0)" class="mt_signin">Already Registered?<br>Login</a></div>-->
                                        <div class="btn-common guest-area"><a onclick="jQuery('#myModal').modal('closeModal');" style="cursor: pointer;">Proceed to Checkout</a></div>
                                 </div>
            </div>
        </div>
    </div>
<script>
   require(['jquery','Magento_Ui/js/modal/modal'],
           function (
                   $,
                   modal
           ) {
                   var modaloption = {
                   type: 'popup',
                           modalClass: 'modal-popup-custom-class',
                           responsive: true,
                           innerScroll: false,
                           clickableOverlay: true,
                           //title: '10% Discount Offer'
                };
                   var callforoption = modal(modaloption, $('.callfor-popup'));
                   //$('.callfor-popup').modal('openModal');
                   //setTimeout(function(){
                     //   $('.callfor-popup').modal('openModal');
                   //}, 1000);
           }
);
</script>
<?php } ?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()) :?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <div class="page-title title-buttons"><h1>Shopping Cart</h1></div>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                    <th class="col item" scope="col"><span></span></th>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                    <th class="col" scope="col"><span></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item) :?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()) :?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
		<div class="cntbtn" style="text-align: center;font-weight: bold;text-align: right;margin-top: 14px;">
	<?php if ($block->getContinueShoppingUrl()) :?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span style="text-decoration: none;color: #464646;"><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
	</div>
    <div class="cart main actions" style="display:none;">
        <?php if ($block->getContinueShoppingUrl()) :?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Add More Products')) ?>">
                <span><?= $block->escapeHtml(__('Add More Products')) ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$itemsVisible = $cart->getQuote()->getAllVisibleItems();
$ProductArray = array();
foreach($itemsVisible as $item)
{
        $ProductArray[] = array("id"=>$item->getSku(),"name"=>$item->getName(),"price"=>$item->getPrice());
        //echo $item->getSku();
}
$product_array_json = json_encode($ProductArray);
?>
<script type="text/javascript">
var firstOrderRuleId = "<?php echo $cart->getQuote()->getAppliedRuleIds() ?>";
if(firstOrderRuleId==5)alert("Congratulations and welcome to Craft Maestros! Your registration is successful. A discount of 10% has been automatically applied on your 1st order.");
var dataLayer = window.dataLayer || [];
dataLayer.push({
  "event": "shoppingCartView",
  "ecommerce": {
    "currencyCode": "INR",
    "detail": {
      "products": <?php echo $product_array_json ?>
    }
  }
});
</script>
<style>
@media only screen and (max-width: 770px) {
.cntbtn {
    margin-top: 16px!important;
	margin-left: 14px!important;
	text-align: left!important;
}
}
</style>
