<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php $_product = $block->getProduct() ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl();
$pUrl = $baseurl.$_product->getUrlPath();
?>


<ul class="sharing-links" style="display:none;">
    <li>
        <?php if ($block->canEmailToFriend()) :?>
            <a href="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product::class)->getEmailToFriendUrl($_product)) ?>"
            class="action mailto friend link-email-friend"><span><?= $block->escapeHtml(__('Email')) ?></span></a>
        <?php endif; ?> 
    </li>
    <li>
	    <a href="javascript:popWin('https://www.facebook.com/sharer/sharer.php?u=<?php echo $_product->getProductUrl(); ?>&t=<?php echo $_product->getName(); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Share on Facebook') ?>" class="link-facebook">Share Facebook</a>
    </li>
    <li>
	    <a href="javascript:popWin('http://twitter.com/home/?status=<?php echo urlencode($_product->getName() . ' (' . $_product->getProductUrl() . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Share on Twitter') ?>" class="link-twitter">Share on Twitter</a>
    </li>
</ul>


<div class="disclamier">
  <p><?php echo $_product->getResource()->getAttribute('disclaimer')->getFrontend()->getValue($_product); ?>

  </p>  
</div>


<div class="desc-container">
    <div class="block-title"><span class="paccordion active"><strong>Details:</strong></span>
        <div class="panel show" style="display:block;">
            <p><?php echo $_product->getResource()->getAttribute('description')->getFrontend()->getValue($_product); ?>

            </p>
        </div>
    </div>
    <div class="block-title"><span class="paccordion nactive"><strong>Dimensions & Care</strong> </span>
        <div class="panel">
            <p><?php echo $_product->getResource()->getAttribute('size_fir')->getFrontend()->getValue($_product); ?></p>
        </div>
    </div>
    <div class="block-title addr-eml"><span class="paccordion nactive"><strong>Shipping & Handling</strong></span>
        <div class="panel">
            <p><?php echo $_product->getResource()->getAttribute('wash_care')->getFrontend()->getValue($_product); ?></p>
        </div>
    </div>
</div>

<div class="disclamier-mobile">
  <p><?php echo $_product->getResource()->getAttribute('disclaimer')->getFrontend()->getValue($_product); ?>

            </p>  
</div>
<!--div class="productSku">PREF - <?php //echo $_product->getSku(); ?></div-->
<!--written by harry-->
<script type="text/javascript">
 require(['jquery'], function () {
jQuery('.paccordion').click(function(e) {
    e.preventDefault();
  
    var $this = jQuery(this);
    
    if (jQuery(this).hasClass('active')) {
        jQuery(".paccordion").each(function() {
           jQuery(this).removeClass('active');
           jQuery(this).addClass('nactive');
        });
    }else{
        jQuery(".paccordion").each(function() {
           jQuery(this).removeClass('active');
           jQuery(this).addClass('nactive');
        });
        $this.removeClass('nactive');
        $this.addClass('active');
    }
  
    if ($this.next().hasClass('show')) {
        $this.next().removeClass('show');
        $this.next().slideUp(350);
    } else {
        $this.parent().parent().find('.block-title .panel').removeClass('show');
        $this.parent().parent().find('.block-title .panel').slideUp(350);
        $this.next().toggleClass('show');
        $this.next().slideToggle(350);
    }
});
 });
function popWin(url,win,para) {
    var win = window.open(url,win,para);
    win.focus();
}
</script>



