<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>

<script>
require(['jquery', 'jquery/ui'], function($){
  jQuery(document).ready( function() {
    // $('body').on("keyup", "input[name=postcode]", function() {
    //     var lenght =  jQuery('input[name=postcode]').val().length;
    //     var pincodevalue =  jQuery('input[name=postcode]').val();
    //     if(lenght == 6){
            
    //                     $.ajax({
    //             type: 'GET',
    //             url: '<?= $block->getBaseUrl(); ?>/citystateauto/',
    //             data: { id: pincodevalue },
    //             cache: false,
    //             success: function(result) {
    //                 if(result.state){                        
    //                     $('select[name="region_id"] option:contains("'+result.state+'")').attr('selected', true);
    //                     $('input[name="city"]').val(result.district).change();
    //                 }
    //             }
    //         });
    //     }
    // });

	jQuery(document).on('change', "[name='country_id']", function () {
	var cname =  jQuery('select[name="country_id"]').find(":selected").val();
 
	if( cname != "" && cname != "IN")
	{
	jQuery("#shipmsg").show();
	}
	else
	{
	jQuery("#shipmsg").hide();
    $("#shipmsg").appendTo("#shipping-new-address-form");
	}
	});
  });
});
</script>
<div id="shipmsg">* Shipping cost for selected country is not added. Get in touch with our team at care@craftmaestros.com to get your order process.</div>
<style>
#shipmsg {
	display:none;
	color: red;
	font-weight: bold;
	width: 100%;
    bottom: 100px;
	left: 38px;
}

@media only screen and (max-width: 767px)
{
	#shipmsg {
	width: 100%!important;
	position: inherit!important;
	}
}
</style>
