<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Cookie settings initialization script
 *
 * @var $block \Magento\Framework\View\Element\Js\Cookie
 */
?>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TCZQGS9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<script type="text/x-magento-init">
    {
        "*": {
            "mage/cookies": {
                "expires": null,
                "path": "<?= $block->escapeJs($block->getPath()) ?>",
                "domain": "<?= $block->escapeJs($block->getDomain()) ?>",
                "secure": false,
                "lifetime": "<?= $block->escapeJs($block->getLifetime()) ?>"
            }
        }
    }
</script>


<!-- Google Tag Manager (noscript) -->
<!--noscript><iframe src="https://www.googletagmanager.com/ns.html?id=UA-146960237-1" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript-->
<!-- End Google Tag Manager (noscript) -->
