<?php

$helper = $this->helper('Meetanshi\Mobilelogin\Helper\Data');
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}

if (!$block->isLoggedIn()) {
    if ($helper->isMobileloginEnabled()) {
        ?>

        <li class="authorization-link sign-link" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
            <a href="javascript:void(0)" class="mt_signin" title="Sign In">
                <?php echo $block->escapeHtml(__('Sign In')); ?>
            </a>
        </li>
        <!--<li class="wishlist">
            <a href="javascript:void(0)" class="cusotom_wishlist" title="Wishlist">
                <?php //echo $block->escapeHtml(__('Wishlist')); ?>
            </a>
        <li>-->

    <?php } else { ?>

        <li>
            <a href="<?php echo $helper->getCreateAccountLink() ?>" class="mt_signin mobile" title="Create an Account">
                <?php echo $block->escapeHtml(__('Create an Account')); ?>
            </a>
        </li>
        <li class="wishlist">
            <a href="<?php echo $block->getUrl('wishlist', ['_secure' => true]);?>" title="wishlist">
                <?php echo $block->escapeHtml(__('Wishlist')); ?>
            </a>
        <li>


    <?php } ?>
<?php } ?>