<?php

$helper = $this->helper('Meetanshi\Mobilelogin\Helper\Data');
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}

if (!$block->isLoggedIn()) {
    if ($helper->isMobileloginEnabled()) {
        ?>
        <div id="customloginpopup">
            <li class="authorization-link sign-link" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
                <a href="javascript:void(0)" class="mt_signin" title="Sign In">
                    <?php echo $block->escapeHtml(__('Sign In')); ?>
                </a>
            </li>
            <!--<li class="wishlist">
                <a href="javascript:void(0)" class="cusotom_wishlist" title="Wishlist">
                    <?php //echo $block->escapeHtml(__('Wishlist')); ?>
                </a>
            <li>-->
        </div>
    <?php } else { ?>
        <div id="customloginpopupelse">
            <li>
                <a href="<?php echo $helper->getCreateAccountLink() ?>" class="mt_signin mobile" title="Create an Account">
                    <?php echo $block->escapeHtml(__('Create an Account')); ?>
                </a>
            </li>
        </div>

    <?php } ?>
<?php } ?>

<script>
require(['jquery', 'jquery/ui'], function($){ 
    $("#customloginpopup").appendTo("#header__item-account");
 });
</script>

<style>
    #customloginpopup{
    z-index: 99;
    position: absolute;
    height: 67px;
    width: 40px;
    opacity: 0;
}
</style>