<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); 
?>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/bootstrap.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/font-awesome.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/jquery.mCustomScrollbar.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/stylefile.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/responsive.css"/>
</form>
<div class="wrap">
    <div class="navnemu">
        <div class="container">
            <div class="row">
                <div class="offset-2 col-8 text-center">
                    <ul class="nav">
                        <li><a href="<?= $block->getUrl('supporttheartisan/index'); ?>">HOME</a></li>
                        <!-- <li><a href="artisans.html">ARTISANS</a></li> -->
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="thanks-banner">
        <img src="<?php echo $this->getViewFileUrl('Kellton_SupportTheArtisan::images/desktop@2x.png'); ?>" alt="">
        <div class="overlay-banner">
            <div class="container">
                <div class="offset-sm-3 col-sm-6">
                    <div class="banner-text-inner">
                        <div class="top-sec">
                            <h5>Thank you</h5>
                            <p>Your support is a ray of hope for our artisan in these grim times.
                                You will receive a specially handcrafted piece from our artisan very soon!</p>
                        </div>
                        <div class="bottom-sec">
                            <p>Explore more about our master artisans and their exquisite crafts at</p>
                            <a href="http://craftmaestros.com/" class="btn btn-light">craftmaestros.com</a>
                        </div>
                        <div class="logo">
                            <img src="<?php echo $this->getViewFileUrl('Kellton_SupportTheArtisan::images/Logo White Desktop.png'); ?>" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="social-link">
            <a href="https://www.instagram.com/craftmaestros/"><img src="<?php echo $this->getViewFileUrl('Kellton_SupportTheArtisan::images/instagram@2x.png'); ?>" alt=""></a>
            <a href="https://www.facebook.com/AmmaraCraftMaestros/"><img src="<?php echo $this->getViewFileUrl('Kellton_SupportTheArtisan::images/Facebook@2x.png'); ?>" alt=""></a>
            <a href="https://in.pinterest.com/craftmaestros/"><img src="<?php echo $this->getViewFileUrl('Kellton_SupportTheArtisan::images/Pinterest@2x.png'); ?>" alt=""></a>
        </div>
    </div>
</div>
 <script type="text/javascript" src="<?php echo $baseurl; ?>pub/media/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="<?php echo $baseurl; ?>pub/media/js/bootstrap.min.js"></script>
<script src="<?php echo $baseurl; ?>pub/media/js/owl.carousel.min.js"></script>
<script src="<?php echo $baseurl; ?>pub/media/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="<?php echo $baseurl; ?>pub/media/js/custom.js?v=1"></script>
