<?php $data = $block->getPostedData(); 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

?>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/bootstrap.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/font-awesome.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/jquery.mCustomScrollbar.min.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/stylefile.css"/>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $baseurl; ?>pub/media/css/responsive.css"/>
<div class="wrap">
    <div class="red-bar">Support the <strong>ARTISAN.</strong> Save the Crafts.</div>
    <div>       
        <div class="container">
            <div class="row">
                
            </div>
            <div class="row">
                <div class="col-sm-12 text-center">
                    <div class="contact-video">
                        <a href="<?php echo $baseurl; ?>supporttheartisan" class="btn video-back" >< Back</a> 
                    </div>
                </div>
            </div>
            <div class="contact-bx">
                
                        <div class="contact-content text-center">
                            <iframe width="800" height="400" src="https://www.youtube.com/embed/qeb6xVOBBk0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                               <!-- <iframe width="800" height="400" src="https://www.youtube.com/embed/s3luirEhogE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>-->
                        </div>
                    
                
            </div>

            </div>
        </div>
    </div>
    <!-- <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <div class="logo"><img src="images/logo for booth-1.png" alt=""></div>
                </div>
                <div class="col-sm-12 text-center">
                    <p>An inisiative of Craft Maestors</p>
                </div>
                <div class="col-sm-12 text-center">
                    <p> &copy Craft Maestors 2020</p>
                </div>
            </div>
        </div>
    </footer> -->
</div>
<!-- <div id="stop" class="scrollTop">
    <span><i class="fa fa-angle-up" aria-hidden="true"></i></span>
</div> -->
<!-- Modal Trams and Conditions-->


  
  <!--<a href="index.html" class="close btn-cut"><span>×</span></button>-->


<div id="popup-modal" style="display:none;">
    <h5 class="modal-title" id="tramsconditionsTitle">Terms & Conditions</h5>
   <p>
            <ul>
                <li>You are voluntarily supporting the lives of the artisans.</li>
                <li>The money will be received first by Ammara Craft Maestros Pvt Ltd. (Company). The Company is in direct contact with national award-winning artisans across the country, and the Company will transfer the amounts so received to the accounts of the artisans directly, after deducting taxes (GST) and direct costs like packaging and logistics.</li>
                <li>The corresponding amounts received from you will be given to one of the master artisans in the craft category chosen by you. This decision will be solely of the Company.</li>
                <li>The artisan will be making a product of the corresponding value of the money received by her/him and the same shall be shipped by the Company to you.</li>
                <li>You will receive an invoice for the full amount given by you.</li>
                <li>You give your consent to be contacted by the Company by email/phone for getting the details like the address for shipment and other matters.</li>
                <li>The products will be made and shipped within 30-90 days from receipt of funds, depending on the lockdown and related conditions.</li>
                <li>In case the product delivery is further delayed due to any other factors or craftsmen conditions, the Company will not be held responsible in any manner.</li>
                <li>The duration of this initiative and the content of the terms and conditions are subject to change at the sole discretion of the Company at any time.</li>
                <li>The Company will not be held responsible for any IP, confidentiality, product, pricing or related matters in any way. The relevant terms and conditions from <a href="www.craftmaestros.com"> www.craftmaestros.com </a> shall apply.</li>
                <li>The products once received at your address, will not be returned. In case of any broken products, please contact our customer care at <a href="www.craftmaestros.com">www.craftmaestros.com</a> or email at <a href="mailto:care@craftmaestros.com">  care@craftmaestros.com</a>.</li>
                <li>For any payment related or other queries or concerns, please contact our customer care at <a href="www.craftmaestros.com"> www.craftmaestros.com </a> or email at  <a href="mailto:care@craftmaestros.com">care@craftmaestros.com</a> .</li>
            </ul>
            </p>
</div>


