<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo __('Eway Bill Number Information') ?></h4>
    </div>
    <fieldset>
        <tr>

            <td class="label"><label><strong><?php echo __('Add Eway Bill Number :') ?></strong></label></td>
            <td class="value"><input class="input-text " type="text" name="eway_bill_no" id="eway_bill_no" value=""  /></td>
        </tr>
    </fieldset>
</div>