<?php 
$helper = $this->helper('Magepow\CancelOrder\Helper\Data');

?>

<div class="cancel-order" id = "cancel_order">
        <button class="track-order-button">
            <a href=""></a> TRACK ORDER
        </button>
        <button class="track-order-button">
            CANCEL ORDER
        </button>
        <button class="track-order-button">
            CONTACT US
        </button>  
</div>