<style>

</style>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl();


?>
 

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="category-products">
                <ul class="products-grid products-grid--max-4-col first last odd">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
						<?php $categories = $_item->getCategoryIds(); ?> 
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item last">' : '</li><li class="item last">' ?>
                        <?php if(in_array(11,$categories)): ?>
							<div class="newarrival">
									<span>NEW</span>
							</div>
						<?php endif; ?>	
						<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-image">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
<?php 
    $sku =$_item->getSku();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
    $product = $productRepository->get($sku);
    $productid = $product->getId();
    //$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
    //$addToCartUrl = $cartHelper->getAddUrl($product);
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
    $addToCartUrl =  $listBlock->getAddToCartUrl($product);

    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $productid]);
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($productid);


$configMgr = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
$childProducts = $configMgr->getUsedProducts($_product,null);
$counter = 0;
$configProduct = 0;
$pprice = 0;
foreach($childProducts as $childProduct) {
   if( $counter == 0 ) { 
	$configProduct = 1;
        $pprice = $childProduct->getPrice();
        $taxValueArray = array("5"=>3,
                                        "6"=>5,
                                        "7"=>12,
                                        "8"=>18,
                                        "9"=>28
                                );
        $productTaxPercentage = 0;
        if (array_key_exists($childProduct->getTaxClassId(),$taxValueArray))
        {
                $productTaxPercentage = $taxValueArray[$childProduct->getTaxClassId()];
                $gst_value   = ((int)$childProduct->getPrice()*(int)$productTaxPercentage)/100; //Invoice GST value of Unit price
                $pprice      = ((int)$childProduct->getPrice() + $gst_value); //Invoice Unit Price with GST

        }
   }
        $counter = $counter + 1;
}

   $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
    $currencyModel = $objectManager->create('Magento\Directory\Model\Currency'); // Instance of Currency Model
    $price =  $pprice; //Your Price
    //get currency symbol by currency code
    $currencyCode = 'INR';
    $currencySymbol = $currencyModel->load($currencyCode)->getCurrencySymbol();
    $precision = 2;   // for displaying price decimals 2 point
    //get formatted price by currency
    $formattedPrice = $currencyModel->format($price, ['symbol' => $currencySymbol, 'precision'=> $precision], false, false);
?>
<?php
	$salable_qty = 0;
	if($product->getTypeId()=='simple')
	{
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        	$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
        	$qty = $StockState->execute($product->getSku());
        	$salable_qty = $qty[0]['qty'];
		$configProduct = 0;
	}
	else{$salable_qty = 1;}
	?>							
							
<?php if ($product->isSaleable()  && $salable_qty) :?>	
<span></span>
<?php else :?>
<?php if ($product->isAvailable() && $salable_qty) :?>
<span></span>
	<?php else :?>
		<div class="ouf-of-stock-list">
                        <div class="stock unavailable"><span>Sold Out</span></div>
                        </div>
	<?php endif; ?>
<?php endif; ?>							
                        <div class="product-info qwerty" style="padding-bottom: 75px; min-height: 131px;">
                            <h2 class="product-name"><a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                             </a></h2>
                             <div class="price-box">
								 <?php 
									if($configProduct) { ?>
									<span class="normal-price"><span class="price"><?php echo $formattedPrice;?></span></span>
									<?php } else{ echo $block->getProductPriceHtml($_item, $type); }
								?>
								</div>
							<div class="actions">
								<div class="wishlist-new">
									<ul class="add-to-links aaa">
									<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
										<li><a href="#"
										   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
											<img src="<?php echo $this->getBaseUrl(); ?>pub/media/images/wishlist.png">
										</a></li>
									<?php endif; ?>
									<li>
                                        <!--a class="weltpixel-quickview weltpixel_quickview_button_v2" data-quickview-url="<?php //echo $baseurl?>weltpixel_quickview/catalog_product/view/id/<?php //echo $_item->getId();?>/" href="javascript:void(0);"><span>Quick Shop</span></a-->

 <?php if ($product->isSaleable()  && $salable_qty) :?>	
<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
    <?php echo $block->getBlockHtml('formkey')?>
    <div style="margin-top: 5px!important;" class="btn">
        <button type="submit" title="Add to Cart" class="action tocart primary">
            <span style="font-size: 11px!important;line-height: 1px!important;">Add to Cart</span>
        </button>
    </div>   
</form>
<?php else :?>
<?php if ($product->isAvailable() && $salable_qty) :?>
		<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
	<?php else :?>
		<div style="display:none;" class="stock unavailable"><span><?= $block->escapeHtml(__('Sold Out')) ?></span></div>
	<?php endif; ?>
<?php endif; ?>
                                    </li>
									</ul>
								</div>
							</div>
                       </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ul>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
   
<?php endif;?>
