<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title"><strong> </strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="block-content">
				<div class="form-subscribe-header">
					<label for="newsletter">Sign up for our newsletter to receive updates, new arrivals &amp; more</label>
				</div>
				<div class="hry-news">
					<div class="field newsletter">
						<div class="control input-box">
							<input name="email" type="email" id="newsletter"
										placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
										data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="actions" id="newsletter-subscribe">
						<button class="button" title="<?php /* @escapeNotVerified */ echo __('Click to Subscribe') ?>" type="submit">
							<?php /* @escapeNotVerified */ //echo __('Subscribe') ?><img src="<?php echo $block->getViewFileUrl('images/next-email.png'); ?>"/>
						</button>
					</div>
				</div>
				<div class="scg-msg">
					<div class="messages">
					</div>
				</div>
			</div>
        </form>
    </div>
</div>


<script>
    require(['jquery'],function($){
        var form = $('#newsletter-validate-detail');
        form.submit(function(e) {
            if(form.validation('isValid')){
                var email = $("#newsletter-validate-detail #newsletter").val();
                var url = form.attr('action');
                var loadingMessage = $('#loading-message');

                if(loadingMessage.length == 0) {
                    form.find('.input-group').append('<div id="loading-message" style="display:none;padding-top:10px;color: red;font-size: 13px;">&nbsp;</div>');
                    var loadingMessage = $('#loading-message');
                }

                e.preventDefault();
                try{
                    loadingMessage.html('Submitting...').show();
                    $('.scg-msg > messages').html();

                    $.ajax({
                        url: url,
                        dataType: 'json',
                        type: 'POST',
                        data: {email: email},
                        success: function (data){
                            if(data.status != "ERROR"){
                                $("#newsletter-validate-detail #newsletter").val('');
                                $('#newsletter-validate-detail .scg-msg > .messages').html('<div class="message-success success message" ><div >' +
                                    data.msg + '</div></div>');
                            }else{
                                $('#newsletter-validate-detail .scg-msg > .messages').html('<div class="message-error error message" >' +
                                    '<div>'+data.msg +'</div></div>');
                            }
                            loadingMessage.html(data.msg);
                        },
                    });
                } catch (e){
                    loadingMessage.html(e.message);
                }
            }
        });
    })
</script>
<!--End our Script-->
