<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php if ($_product->getNewArrival()){ ?> 
                         <div class="newarrival">
                            <span>NEW</span>
                        </div>
                    <?php } ?>
				<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$product_obj = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());	
				if(isset($product_obj->getTierPrice()[0]['percentage_value']))
				{
				$costPricePercentage = $product_obj->getTierPrice()[0]['percentage_value'];
				$costPriceQty = $product_obj->getTierPrice()[0]['price_qty'];
				if($costPricePercentage && $costPriceQty == 1)
				{ ?>

				<div class="custom-discount-tag">
					<span style="display:none;">Discount: </span> 
					<span class="percentage">-<?php echo number_format($costPricePercentage, 0, '.', ''); ?>%</span> 
				</div>
				<?php }} ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
										<a href="#"
										   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="link-wishlist wishlistoncat" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
											<img src="<?php echo $mediaUrl; ?>images/wishlist.png">
										</a>
									<?php endif; ?>
                                    
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
	<?php
	$salable_qty = 0;
	if($_product->getTypeId()=='simple')
	{
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        	$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
        	$qty = $StockState->execute($_product->getSku());
        	$salable_qty = $qty[0]['qty'];
	}
	else{$salable_qty = 1;}
	?>
               <div class="ouf-of-stock-list">
                    <?php if ($_product->isSaleable()  && $salable_qty) :?>
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form"
                              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                              method="post">
                            <input type="hidden"
                                   name="product"
                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                            <?= $block->getBlockHtml('formkey') ?>
                            <button type="submit"
                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                    class="action tocart primary">
                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                            </button>
                        </form>
                    <?php else :?>
                        <?php if ($_product->isAvailable() && $salable_qty) :?>
                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                        <?php else :?>
                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Sold Out')) ?></span></div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>

            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
