<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
 <?php
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl();

$attr = $block->getProduct()->getResource()->getAttribute("craftsman_name");
    $artist_text=$attr->getSource()->getOptionText($block->getProduct()->getCraftsmanName());
   $atrist_url= "craftsman/".str_replace(" ","-",strtolower($artist_text)).".html";
?>
<div class="product-name">
     <span class="h1"><?php echo $block->getProduct()->getName();?> </span>
</div>

<div class="three-des">
  <a href="<?php  echo $baseurl.$atrist_url;  ?>" ><h2><?php echo "".$artist_text; ?></h2></a>  </div>


<?php if($block->getProduct()->getTypeId()=='simple' && $block->getProduct()->getSize()){ ?>
<div class="size-box">
	<p>SIZE <span><?php echo $block->getProduct()->getSize() ?></span>

	</p>
</div>
<?php } ?>

<!-- <?= $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
 -->