<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
      <div class="page-title"><h1>Forgot Your Password?</h1></div>
      <div class="fieldset">
            <h2 class="legend">Retrieve your password here</h2>
            <p>Please enter your email address or username below. You will receive a link to reset your password.</p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email Address/Username')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
            <p class="back-link"><a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>" onclick="return false;"><small>« </small>Back to Login</a></p>
            <button type="submit" title="Submit" class="button">
            <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
    </div>
</form>
