<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\View */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @noEscape */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>
<?php
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();
?>


<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product

$_product = $block->getProduct();
$count = 0;
foreach ($_product->getOptions() as $o) {
        /*$title = $o->getTitle();
         $vdata = (explode(',', $title));
         $skdk = array_diff($vdata, array("Personalized Card", "Gift Message"));
         foreach($skdk as $kk){
         $sbox = $kk;
         }
   */      
	if ($o->getTitle() == 'Special Box') {  ?>
        <div class="gift-image"><span id="giftboxesimageid" class="giftboxes"><img src="<?php echo $url.'pub/media/images/GIFT.jpg';?>"></span></div>
<?php } $count++;} ?>

<style>

 .giftboxes {
       //position: absolute;margin-top:-100px;
}
.gift-image{ 
    float: left;
    width: 100%;
    //margin-bottom: 31px;
    //margin-left: 165px;
}
label[for="options_3"] {
    //display: none;
}
input#options_3 {
    //display: none;
}
@media (max-width: 767px)
{
	.giftboxes {
       //position: absolute;margin-top:30px;
}
}
</style>
