<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center">
            <?php /* @escapeNotVerified */ echo __('Order Value (Month Wise)'); ?>
        </h3>
    </div>
    <div class="panel-body">
        <div class="chart" id="earnings-chart"></div>
    </div>
</div>
<div class="panel panel-default charts">
    <div class="panel-heading">
        <h3 class="panel-title text-center">
            <?php /* @escapeNotVerified */ echo __('Order Quantity (Month Wise)'); ?>
        </h3>
    </div>
    <div class="panel-body">
        <div class="chart" id="amount-chart"></div>
    </div>
</div>